kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ template "serviceAccount" . }}-role
  namespace: {{ template "namespace" . }}
rules:
- apiGroups: [""]
  resources: ["endpoints"]
  verbs: ["get", "watch", "list", "delete", "update", "create"]
- apiGroups: ["coordination.k8s.io"]
  resources: ["leases"]
  verbs: ["get", "watch", "list", "delete", "update", "create"]
