kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ template "serviceAccount" . }}-binding
  namespace: {{ template "namespace" . }}
subjects:
  - kind: ServiceAccount
    name: {{ template "serviceAccount" . }}
    namespace: {{ template "namespace" . }}
roleRef:
  kind: ClusterRole
  name: {{ template "serviceAccount" . }}-runner
  apiGroup: rbac.authorization.k8s.io
