kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ template "serviceAccount" . }}-binding
  namespace: {{ template "namespace" . }}
subjects:
  - kind: ServiceAccount
    name: {{ template "serviceAccount" . }}
    namespace: {{ template "namespace" . }}
roleRef:
  kind: Role
  name: {{ template "serviceAccount" . }}-role
  apiGroup: rbac.authorization.k8s.io
