{{- if not .Values.configName }}
apiVersion: v1
kind: ConfigMap
metadata:
    name: {{ template "name" . }}
    namespace: {{ template "namespace" . }}
data:
    xcpng-csi.conf: |-
      {{- toYaml .Values.config | nindent 8 }}
{{- end }}
